modLoader="javafml"
loaderVersion="[39,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/ZekerZhayard/AutoReconnect/issues"

[[mods]]
modId="autoreconnect"
version="${file.jarVersion}"
displayName="AutoReconnet"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/autoreconnect-forge"
logoFile="icon16.png"
#credits="Thanks for this example mod goes to Java"
authors="Bstn1802, ZekerZhayard"
description='''
This mod will automatically try to reconnect you back to a server if you got disconnected.
By default, it will make 4 attempts after 3, 10, 30 and 60 seconds.
'''

[[dependencies.autoreconnect]]
modId="forge"
mandatory=true
versionRange="[39.0,41.0)"
ordering="NONE"
side="CLIENT"

[[dependencies.autoreconnect]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="CLIENT"

[[dependencies.autoreconnect]]
modId="cloth_config"
mandatory=true
versionRange="[6.0.0,)"
ordering="NONE"
side="CLIENT"
